FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .

RUN --mount=type=cache,target=/root/.cache/go-build \
    go build -v -o weather-service ./cmd/weatherApi/weather.go


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/weather-service /app/weather-service

CMD ["./weather-service"]